blank_issues_enabled: false
contact_links:
  - name: Support général
    url: https://github.com/ton-compte/ton-depot/discussions
    about: Si votre demande ne correspond à aucune des catégories ci-dessus, utilisez les discussions.
