name: Lint Code

on:
  push:
    branches:
      - main
      - develop
      - feature/** # Inclure toutes les branches de fonctionnalités
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Remplace par la version de Node.js que tu utilises

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npx eslint .
